/* ========================================
   CV DATA — rediger alt innhold her
   L       = aktivt språk (no/en)
   EX      = arbeidserfaring
   T       = UI-tekster (no + en)
======================================== */

var L='no',AF=null,_dr=null,_st=null;
var EX=[
{y:"2024",c:{no:"Arctic Systems AS",en:"Arctic Systems AS"},r:{no:"Principal Architect",en:"Principal Architect"},d:{no:"Leder arkitekturteamet i en av Norges raskest voksende SaaS-bedrifter.",en:"Leading the architecture team at one of Norway's fastest growing SaaS companies."},b:{no:["Designet multi-cloud-arkitektur (AWS+Azure) for 5M+ daglige brukere","Reduserte latens med 60% via edge-caching","Bygde og mentoret team p\u00e5 14 ingeni\u00f8rer"],en:["Designed multi-cloud architecture for 5M+ daily users","Reduced latency 60% via edge-caching","Built and mentored a team of 14 engineers"]},t:["Cloud Architecture","Kubernetes","TypeScript","Team Lead"]},
{y:"2023",c:{no:"Arctic Systems AS",en:"Arctic Systems AS"},r:{no:"Staff Engineer",en:"Staff Engineer"},d:{no:"Teknisk ankerpunkt for produktplattform-teamet. Null nedetid ved kritisk migrering.",en:"Technical anchor for product platform team. Zero-downtime critical migration."},b:{no:["Migrerte 40+ mikrotjenester fra ECS til Kubernetes uten nedetid","Innf\u00f8rte SLO-rammeverk og on-call-kultur","Kafka-pipeline for sanntidsanalyse"],en:["Migrated 40+ microservices to Kubernetes with zero downtime","Established SLO framework and on-call culture","Kafka pipeline for real-time analytics"]},t:["Kubernetes","Kafka","Terraform","SLO"]},
{y:"2022",c:{no:"Fjord Digital",en:"Fjord Digital"},r:{no:"Senior Backend Engineer",en:"Senior Backend Engineer"},d:{no:"Full eierskap over backend for fintech-plattform med 500k brukere.",en:"Full ownership of backend for fintech platform with 500k users."},b:{no:["Bygde betalings-API mot Vipps, Stripe og BankID","Event-drevet arkitektur med idempotente handlers","Test-coverage fra 38% til 89%"],en:["Built payment API for Vipps, Stripe and BankID","Event-driven architecture with idempotent handlers","Test coverage from 38% to 89%"]},t:["Go","PostgreSQL","gRPC","Fintech"]},
{y:"2021",c:{no:"Fjord Digital",en:"Fjord Digital"},r:{no:"Backend Engineer",en:"Backend Engineer"},d:{no:"Del av kjerneteamet som lanserte f\u00f8rste B2B-produkt.",en:"Part of core team that launched the first B2B product."},b:{no:["Multi-tenant autentisering og autorisasjonsmotor","RFC-prosess for API-design standarder","Onboardet og mentoret tre juniorer"],en:["Multi-tenant authentication and authorization engine","API design RFC process","Onboarded and mentored three junior engineers"]},t:["Go","Auth","GraphQL"]},
{y:"2020",c:{no:"Cognite AS",en:"Cognite AS"},r:{no:"Software Engineer",en:"Software Engineer"},d:{no:"Industriell data-plattform brukt av ledende energiselskaper globalt.",en:"Industrial data platform used by global energy leaders."},b:{no:["Python SDK for tidsseriedata - 3000+ GitHub-stjerner","Bulk-import-pipeline, 4x gjennomstr\u00f8m","Innhentet enterprise-tilbakemeldinger"],en:["Python SDK for time series data - 3000+ GitHub stars","Bulk import pipeline, 4x throughput","Gathered enterprise customer feedback"]},t:["Python","TimeSeries","Industrial IoT","SDK"]},
{y:"2019",c:{no:"Cognite AS",en:"Cognite AS"},r:{no:"Software Engineer",en:"Software Engineer"},d:{no:"Frontend og integrasjonsarbeid p\u00e5 visualiseringsverkt\u00f8y.",en:"Frontend and integration work on visualization tooling."},b:{no:["Interaktivt 3D-visualiseringsverkt\u00f8y for prosessanlegg","OPC-UA datastr\u00f8m mot sanntids dashboard","Due diligence under Series B"],en:["Interactive 3D visualization tool for process plants","OPC-UA data stream to real-time dashboard","Due diligence for Series B"]},t:["React","TypeScript","3D Viz","OPC-UA"]},
{y:"2018",c:{no:"Bekk Consulting",en:"Bekk Consulting"},r:{no:"Konsulent",en:"Consultant"},d:{no:"Konsulentarbeid offentlig og privat sektor, legacy-modernisering.",en:"Consulting for public and private sector, legacy modernization."},b:{no:["Frontend-modernisering for NAV (React)","Teknisk vurdering for tre kunder","Interne CI/CD-workshops"],en:["Frontend modernization for NAV (React)","Technical assessment for three clients","Internal CI/CD workshops"]},t:["React","Legacy Migration","CI/CD","Public Sector"]},
{y:"2017",c:{no:"Bekk Consulting",en:"Bekk Consulting"},r:{no:"Junior Konsulent",en:"Junior Consultant"},d:{no:"F\u00f8rste \u00e5r som konsulent, rotasjon mellom fire engasjementer.",en:"First year as consultant, rotating across four engagements."},b:{no:["Fullstack for logistikkselskap (Node.js + React)","DevOps-transformasjon hos forsikringsselskap","Presenterte funn til C-suite"],en:["Fullstack for logistics company (Node.js + React)","DevOps transformation at insurance company","Presented findings to C-suite"]},t:["Node.js","React","DevOps","Logistics"]},
{y:"2016",c:{no:"Webstep AS",en:"Webstep AS"},r:{no:"Utvikler",en:"Developer"},d:{no:"IT-konsulent, Java-backends og systemintegrasjon.",en:"IT consultant, Java backends and system integration."},b:{no:["Integrasjonsplatform mellom ERP og CRM","REST-APIer for 12 interne systemer","Arkitekturgr\u00e5dgivning for lokal kommune"],en:["Integration platform between ERP and CRM","REST APIs for 12 internal systems","Architecture advisory for municipality"]},t:["Java","Spring Boot","REST","Integration"]},
{y:"2015",c:{no:"Webstep AS",en:"Webstep AS"},r:{no:"Graduate Developer",en:"Graduate Developer"},d:{no:"F\u00f8rste stilling etter studier, vekst fra junior til selvstendig.",en:"First position post-graduation, junior to independent contributor."},b:{no:["Enterprise Java-utvikling med Spring","Migrering av legacy Oracle Forms","AWS Foundation-sertifisering"],en:["Enterprise Java development with Spring","Migration of legacy Oracle Forms","Obtained AWS Foundation certification"]},t:["Java","Spring","Oracle","AWS"]},
{y:"2014",c:{no:"NTNU / Studentjobb",en:"NTNU / Student job"},r:{no:"Studentassistent & Dev",en:"Teaching Assistant & Dev"},d:{no:"Kombinerte mastergradsarbeid med deltidsstillinger.",en:"Combined master's degree with part-time positions."},b:{no:["Undervisningsassistent i Algoritmer og Datastrukturer","Freelance webutvikling (PHP/WordPress)","Masteroppgave: Distribuert konsensus i ad-hoc nettverk"],en:["Teaching assistant for Algorithms and Data Structures","Freelance web development (PHP/WordPress)","Master's thesis: Distributed consensus in ad-hoc networks"]},t:["Teaching","PHP","Research","Distributed Systems"]}
];
var T={
no:{t1:"CV",t2:"Om meg",t3:"Kontakt",sl1:"\u00c5rs erfaring",sl2:"Prosjekter",sl3:"Sertifiseringer",sl4:"Land",lsk:"Kjernekompetanse",lex:"Arbeidserfaring",led:"Utdanning",lval:"Verdier & Arbeidsform",lint:"Interesser",llng:"Spr\u00e5k",lci:"Kontaktinfo",lph:"Telefon",lloc:"Sted",lweb:"Nettside",lsend:"Send melding",sl:"Send melding \u2192",pdfl:"Last ned PDF",lfw:"Vis kun jobb",lfwo:"Tilbake til full visning",lfe:"Vis kun utdanning",lfeo:"Tilbake til full visning",asl:"Legg til kompetanse",ayl:"Legg til \u00e5r / stilling",ael:"Legg til utdanning",avl:"Legg til verdi",ail:"Legg til interesse",all:"Legg til spr\u00e5k",addb:"+ punkt",addt:"+ tag",ehint:"Klikk p\u00e5 tekst for \u00e5 redigere \u2014 bruk + for \u00e5 legge til og \u00d7 for \u00e5 fjerne",sav:"\u2713 Lagret",dc:"Slett denne stillingen?",er:"Fyll inn navn, e-post og melding.",ee:"E-postadressen ser ikke riktig ut.",om:"\u2713 \u00c5pner e-post...",fln:"Ditt navn",fle:"E-postadresse",fls:"Emne",flm:"Melding",mu:"\u2191",md:"\u2193",ain:"Jeg er en <em>nysgjerrig teknolog</em> med et hjerte for elegante systemer og team som faktisk stortrives.",ap1:"Vokste opp i Troms\u00f8 med fjordene rett utenfor vinduet. Fascinasjon for hvordan ting henger sammen ledet meg til informatikk ved NTNU og siden til en karriere der jeg har f\u00e5tt bygge systemer som faktisk betyr noe.",ap2:"Jeg trives best i skj\u00e6ringspunktet mellom arkitektur og teamledelse. God kode er prosa: lesbar, velstrukturert og med mening bak hvert valg.",vh1:"Langsiktig tenkning",vp1:"Arkitektur som varer. Beslutninger tatt med fremtiden i sikte.",vh2:"Refleksjon og nyanser",vp2:"Gode beslutninger krever rom til \u00e5 se saken fra flere sider.",vh3:"Tydelig kommunikasjon",vp3:"Teknisk kompleksitet forklart enkelt \u2014 fordi det er viktig.",vh4:"Kontinuerlig l\u00e6ring",vp4:"Teknologi er bevegelig m\u00e5l. Nysgjerrigheten holder meg i forkant.",in1:"Styrketrening",in2:"Ern\u00e6ring",in3:"Gitar",in4:"Kommunikasjon",in5:"Frisbeegolf",in6:"Sykling",ch2:"La oss ta en prat \u2615",csub:"Enten det gjelder spennende prosjekter, stillinger, eller bare en god teknologidiskusjon.",avail:"\u00c5pen for nye muligheter fra Q3 2025",locv:"Oslo, Norge"},
en:{t1:"Resume",t2:"About me",t3:"Contact",sl1:"Years exp.",sl2:"Projects",sl3:"Certifications",sl4:"Countries",lsk:"Core Skills",lex:"Work Experience",led:"Education",lval:"Values & Work Style",lint:"Interests",llng:"Languages",lci:"Contact Info",lph:"Phone",lloc:"Location",lweb:"Website",lsend:"Send a message",sl:"Send message \u2192",pdfl:"Download PDF",lfw:"Show work only",lfwo:"Back to full view",lfe:"Show education only",lfeo:"Back to full view",asl:"Add skill",ayl:"Add year / position",ael:"Add education",avl:"Add value",ail:"Add interest",all:"Add language",addb:"+ point",addt:"+ tag",ehint:"Click any text to edit \u2014 use + to add and \u00d7 to remove",sav:"\u2713 Saved",dc:"Delete this position?",er:"Please fill in name, email and message.",ee:"That email address doesn't look right.",om:"\u2713 Opening mail...",fln:"Your name",fle:"Email address",fls:"Subject",flm:"Message",mu:"\u2191",md:"\u2193",ain:"I'm a <em>curious technologist</em> with a heart for elegant systems and teams that genuinely thrive.",ap1:"Grew up in Troms\u00f8 with fjords just outside the window. An early fascination with how things connect led me to computer science at NTNU, and since then to a career building systems that genuinely matter.",ap2:"I thrive at the intersection of architecture and team leadership. Good code is prose: readable, well-structured, and with intent behind every choice.",vh1:"Long-term thinking",vp1:"Architecture that lasts. Decisions made with the future in mind.",vh2:"Reflection & nuance",vp2:"Good decisions need time to breathe \u2014 looking at a situation from multiple angles.",vh3:"Clear communication",vp3:"Technical complexity explained simply \u2014 because it matters.",vh4:"Continuous learning",vp4:"Technology is a moving target. Curiosity keeps me ahead.",in1:"Strength training",in2:"Nutrition",in3:"Guitar",in4:"Communication",in5:"Disc golf",in6:"Cycling",ch2:"Let's have a chat \u2615",csub:"Whether it's an exciting project, a position, or just a good tech discussion.",avail:"Open to new opportunities from Q3 2025",locv:"Oslo, Norway"}
};
